services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mattermost-helper
    restart: unless-stopped
    ports:
      - '8080:8080'
    env_file:
      - .env
